#!/bin/sh

ember-precompile emberjs/templates/*.handlebars plugins/*/*.handlebars -f public/javascripts/templates.js
cat plugins/transnodeFrontendPlugin.js plugins/*/frontend.js > public/javascripts/plugins.js
